(function (g) {
  "use strict";
  const Nertz = (g.Nertz = g.Nertz || {});
  Nertz.storyContent = {
    meta: {
      title: "Nertz Royale: The Sandpiper Revival",
      tagline: "One boarded-up card club. One washed-up town. One summer to deal yourself back in.",
    },
    cast: {
      you: { name: "You", emoji: "🧑" },
      betts: { name: "Bettina \"Betts\" Marlowe", emoji: "⚓" },
      preston: { name: "Preston Featherstonhaugh III", emoji: "🎩" },
      doreen: { name: "Doreen Vasquez", emoji: "🥣" },
      gus: { name: "Gus \"Foghorn\" Tibbetts", emoji: "📢" },
      milo: { name: "Milo Pénzes", emoji: "📊" },
      ferdinand: { name: "Postmaster Ferdinand Ossola", emoji: "📮" },
      crumbs: { name: "Admiral Crumbs", emoji: "🐦" },
      trent: { name: "Trent (Compliance)", emoji: "📋" },
    },
    locations: [
      { id: "club", name: "The Sandpiper Social Club", emoji: "🏚️", blurb: "Boarded-up HQ of Gullwash card culture. Sign missing half its letters. Floor missing some of its dryness." },
      { id: "baitshop", name: "The Bait & Wait", emoji: "🎣", blurb: "Gus's bait shop, tackle counter doubling as a card table since approximately forever." },
      { id: "chowder", name: "Doreen's Chowder Cathedral", emoji: "🍲", blurb: "Part diner, part shrine, all chowder. Blackjack dealt between soup courses." },
      { id: "pier", name: "Gullwash Pier", emoji: "🎡", blurb: "Salt-bleached boardwalk, one derelict mini-golf course, and a paper route that never stops." },
      { id: "lighthouse", name: "Point Bickerstaff Lighthouse", emoji: "💡", blurb: "Automated since 1994, unofficially reopened for midnight card lessons." },
      { id: "marina", name: "Gullwash Marina", emoji: "🛥️", blurb: "Preston's yacht, The Humble Brag, moored where everyone can admire it whether they want to or not." },
    ],
    beats: [
      {
        id: "b1", locationId: "club", type: "dialogue", title: "Welcome Back to Gullwash",
        intro: [
          { who: "betts", text: "Welcome home, kid. Don't mind the smell — that's not the club, that's the town." },
          { who: "preston", text: "The prodigal deckhand returns! Preston Featherstonhaugh — pronounced 'Fanshaw.' The rest is decorative." },
          { who: "betts", text: "Charter says the club stands as long as it fields a Founder's Day champion. Congratulations. You're it." },
          { who: "preston", text: "Come Founder's Day, this eyesore becomes Gullwash's first artisanal kelp-smoothie conservatory." },
          { who: "betts", text: "Mind the water feature in the corner. Not a leak — ambience. As the old sailors say: a wet floor is... a floor that's wet. Think about it." },
          { who: "betts", text: "...Well said, kid. Truly. Grab a broom. Destiny's dusty." },
        ],
        reward: { xp: 60, coins: 15 },
      },
      {
        id: "b2", locationId: "club", type: "nertz", title: "Shake Off the Rust",
        intro: [
          { who: "betts", text: "Ten coins says you've still got it. If not, ten coins buys me the pleasure of watching." },
          { who: "betts", text: "Fundamentals: aces up the middle, panic on the inside." },
          { who: "betts", text: "As the old sailors say: shuffle like the tide, deal like the... other tide. There's two tides. It works." },
          { who: "crumbs", text: "(lands on the table, already eyeing the ace pile)" },
          { who: "betts", text: "Ferdinand keeps a ledger for what that bird steals. 'Aces, Lost at Sea(gull).' Try to keep all four this time." },
        ],
        win: [{ who: "betts", text: "You won. Good. I had something inspiring prepared either way, but this saves us both the embarrassment." }],
        lose: [{ who: "betts", text: "Lost to your own grandmother's oldest friend. Sit with that. Then sit back down — best of three." }],
        nertz: {
          bots: [{ name: "Betts", avatar: "⚓", difficulty: "easy" }],
          rules: {},
          objective: { type: "win" },
        },
        reward: { xp: 70, coins: 20 },
      },
      {
        id: "b3", locationId: "baitshop", type: "nertz", title: "Low Tide Rules",
        intro: [
          { who: "gus", text: "GUS TIBBETTS EYES THE NEWCOMER. THE CROWD — one bucket of chum — GOES WILD." },
          { who: "gus", text: "House rules: seven-card Nertz pile. Low tide. Short stack, short game, short goodbyes." },
          { who: "gus", text: "(switches to his \"indoor voice\") THIS IS MY INDOOR VOICE. NOBODY KNOWS WHY IT'S LOUDER." },
          { who: "gus", text: "GUS FLIPS THE STOCK. IT'S A THREE. THE CROWD IS SILENT. BECAUSE IT'S BAIT." },
          { who: "gus", text: "Fifteen coins on the line. GUS HAS NEVER FELT MORE ALIVE, OR MORE LIKELY TO LOSE." },
        ],
        win: [{ who: "gus", text: "GUS TIBBETTS IS DEFEATED BY A CHILD HE TAUGHT TO SHUFFLE. GUS COULDN'T BE PROUDER. GUS IS CRYING A LITTLE." }],
        lose: [{ who: "gus", text: "UNBELIEVABLE SCENES. THE NEWCOMER FOLDS LIKE WET CHUM. GUS REMAINS UNDEFEATED AND INSUFFERABLE." }],
        nertz: {
          bots: [{ name: "Gus \"Foghorn\" Tibbetts", avatar: "📢", difficulty: "easy" }],
          rules: { nertzSize: 7 },
          objective: { type: "time", target: 180 },
        },
        reward: { xp: 85, coins: 25 },
      },
      {
        id: "b4", locationId: "chowder", type: "blackjack", title: "Hit, Stand, or Soup",
        intro: [
          { who: "doreen", text: "Table minimum is twenty coins or one chowder. Coins are worth less." },
          { who: "doreen", text: "Hit, stand, or soup? Everyone says hit. Nobody ever says soup. I keep offering." },
          { who: "doreen", text: "My endorsement carries this whole boardwalk. Beat my table and it's yours. Lose and it's also yours, but sadder." },
          { who: "crumbs", text: "(perches on the menu board, judging your basic strategy)" },
          { who: "doreen", text: "Dealer's showing sixteen. That's broth with no clams in it. Nervous soup. Your move." },
        ],
        win: [
          { who: "doreen", text: "Twenty-one! Same as the chowders simmering out back. It's a sign. Everything's a sign once you've had enough chowder." },
          { who: "doreen", text: "Fine — my endorsement, AND a punch card. Nine more blackjacks and the tenth chowder's free." },
        ],
        lose: [{ who: "doreen", text: "Busted. Comfort soup's on the house. Consider it a tuition payment to the University of Doreen." }],
        stake: 20,
        opponent: { name: "Doreen Vasquez", avatar: "🥣" },
        reward: { xp: 95, coins: 30 },
      },
      {
        id: "b5", locationId: "pier", type: "nertz", title: "Honest at the Pier",
        intro: [
          { who: "milo", text: "We flip the stock one card at a time. Flipping three is 34% dishonest. We're honest at the pier." },
          { who: "milo", text: "Against me and Ferdinand you have a 31% chance. I made that up. But I said it confidently, which adds 40%." },
          { who: "ferdinand", text: "I once delivered a postcard that said only 'NERTZ.' No address. No stamp. I think about it every day." },
          { who: "ferdinand", text: "Oh no. I have three aces buried. I should not have said that out loud. I say everything out loud." },
          { who: "milo", text: "Twenty-five coins says the wind is also against you. The wind has no stated position. I'm extrapolating." },
        ],
        win: [
          { who: "milo", text: "You beat a 31% chance I invented. Statistically this means I owe you an apology and possibly the ocean." },
          { who: "ferdinand", text: "Dear Mother. The newcomer won. I am happy for them. I am also composing this while losing. Multitasking." },
        ],
        lose: [{ who: "milo", text: "As predicted! Well — as retroactively predicted. I'll adjust my numbers to fit. That's still science." }],
        nertz: {
          bots: [
            { name: "Milo Pénzes", avatar: "📊", difficulty: "normal" },
            { name: "Postmaster Ferdinand Ossola", avatar: "📮", difficulty: "normal" },
          ],
          rules: { stockFlip: 1 },
          objective: { type: "score", target: 15 },
        },
        reward: { xp: 110, coins: 35 },
      },
      {
        id: "b6", locationId: "club", type: "poker", title: "Postal Poker Night",
        intro: [
          { who: "ferdinand", text: "Postal Poker Night rules: five-card draw, heads up, and I narrate my feelings. Doctors are baffled." },
          { who: "ferdinand", text: "I draw two. 'Dear Mother. I have kept the kings. I am invincible. Wish you were here.'" },
          { who: "betts", text: "Careful, kid — the water feature's up to the table legs now. Everyone agrees this is fine." },
          { who: "ferdinand", text: "Your face says nothing. NOTHING. The most beautiful poker face I've ever seen. I may weep. You'll know — I'll announce it." },
          { who: "crumbs", text: "(steals the ace of hearts off Ferdinand's discard pile mid-shuffle)" },
          { who: "ferdinand", text: "The ledger grows. 'Aces, Lost at Sea(gull),' entry forty-one. Mother would be so disappointed in this bird." },
        ],
        win: [{ who: "ferdinand", text: "'Dear Mother. I bluffed. It went how it always goes. The chowder here remains excellent.'" }],
        lose: [{ who: "ferdinand", text: "'Dear Mother. I won. I do not know how to feel about winning. Please advise by return post.'" }],
        stake: 35,
        opponent: { name: "Postmaster Ferdinand Ossola", avatar: "📮" },
        reward: { xp: 125, coins: 40 },
      },
      {
        id: "b7", locationId: "chowder", type: "nertz", title: "Six Burners, Six Piles",
        intro: [
          { who: "doreen", text: "Six work piles. One for each burner on my stove. That's not a rule, it's a lifestyle." },
          { who: "gus", text: "(indoor voice, somehow the loudest sound in the room) GUS AND DOREEN. THE TAG TEAM NOBODY ASKED FOR." },
          { who: "doreen", text: "If I win, the club serves chowder at every match. If I lose, same deal. I've thought this through." },
          { who: "gus", text: "Gus reaches for the two of hearts. Gus knocks over his own Nertz pile. Gus is being very brave about it." },
          { who: "doreen", text: "Forty coins on the table, and my espresso's stronger than my resolve to lose gracefully." },
        ],
        win: [
          { who: "doreen", text: "You beat both of us AND the sticky table. Respect. Chowder's on every table now. Was gonna happen anyway." },
          { who: "gus", text: "GUS AND DOREEN, DEFEATED. GUS BLAMES THE TABLE. THE TABLE CANNOT DEFEND ITSELF. THE TABLE IS STICKY, NOT GUILTY." },
        ],
        lose: [{ who: "doreen", text: "Six burners, six piles, one very smug chowder queen. Soup's still on the house. I'm not a monster." }],
        nertz: {
          bots: [
            { name: "Doreen Vasquez", avatar: "🥣", difficulty: "normal" },
            { name: "Gus \"Foghorn\" Tibbetts", avatar: "📢", difficulty: "normal" },
          ],
          rules: { workPiles: 6 },
          objective: { type: "win" },
        },
        reward: { xp: 140, coins: 50 },
      },
      {
        id: "b8", locationId: "pier", type: "golf", title: "The Old Ways",
        intro: [
          { who: "betts", text: "Golf solitaire. One card up, chip the rest onto it, no mulligans. The old ways." },
          { who: "gus", text: "A card game about GOLF? Who'd sit through a whole story about golf? Nobody. Not even with a great soundtrack." },
          { who: "betts", text: "As the old sailors say: par is just a number the sea gave us. ...The sea did not give us that. I don't know where numbers come from." },
          { who: "betts", text: "Win and the forty-five's yours. Bogey it and you're painting the clubhouse. Either way, the clubhouse gets painted." },
          { who: "milo", text: "Statistically, golf solitaire has a 60% patience requirement. I have none. I'm leaving before this starts." },
        ],
        win: [{ who: "betts", text: "Clean round. The old ways still work. Don't tell the new ways — they're sensitive about it." }],
        lose: [{ who: "betts", text: "Bogey. Grab a brush, kid. The clubhouse isn't gonna paint itself, and I already told you it would either way." }],
        stake: 55,
        opponent: { name: "Bettina \"Betts\" Marlowe", avatar: "⚓" },
        config: { target: 24 },
        reward: { xp: 155, coins: 55, unlockTheme: "sakura" },
      },
      {
        id: "b9", locationId: "club", type: "nertz", title: "The Beveling Incident",
        intro: [
          { who: "preston", text: "My interns: Bryce, and the other Bryce. They train four hours daily and are legally unable to blink." },
          { who: "trent", text: "Before we begin, liability waivers. Three copies. Initial here, here, and — is that the water feature? Initial that too." },
          { who: "preston", text: "Regulation eighteen-card Nertz pile, per the Featherstonhaugh Rulebook. Which I wrote. And pronounce correctly." },
          { who: "preston", text: "It's FAN-shaw. F-E-A-T-H-E-R-S-T-O-N-H-A-U-G-H. English is a scam, and I happen to be winning it." },
          { who: "betts", text: "As the old sailors say: some days you're the gull, some days you're the chum. Today, chum. Tomorrow, practice." },
        ],
        win: [
          { who: "preston", text: "Oh dear — a technicality. Your cards are insufficiently beveled. Match voided, key forfeited." },
          { who: "trent", text: "Per waiver clause 4(c), the key is now a 'procedural deposit.' Nobody reads clause 4(c)." },
        ],
        lose: [{ who: "preston", text: "No technicality needed this time. Bryce, note the time. The other Bryce, note it again, for redundancy." }],
        nertz: {
          bots: [
            { name: "Bryce", avatar: "🤖", difficulty: "hard" },
            { name: "The Other Bryce", avatar: "🤖", difficulty: "hard" },
          ],
          rules: { nertzSize: 18 },
          objective: { type: "score", target: 20 },
        },
        reward: { xp: 160, coins: 20 },
      },
      {
        id: "b10", locationId: "lighthouse", type: "nertz", title: "Squall Speed",
        intro: [
          { who: "betts", text: "Lighthouse rules. I play at full squall speed, the lamp lights the table every four seconds. Build in the dark." },
          { who: "betts", text: "Fifty-five coins on the table. I borrowed them from you earlier, so this is emotionally complicated for both of us." },
          { who: "milo", text: "I researched 'The Squall,' 1987. Betts played Nertz during an actual squall. Winner: the squall. By four cards." },
          { who: "betts", text: "Believe in the light. As the old sailors say: the storm doesn't beat you. It just plays faster. That one's real. I was there." },
          { who: "crumbs", text: "(circles the beam overhead, waiting for an ace to make a break for it)" },
        ],
        win: [{ who: "betts", text: "There it is. Squall speed, and you kept pace. I haven't seen hands like that since I had these hands." }],
        lose: [{ who: "betts", text: "Not tonight. The lamp keeps its own schedule, and it doesn't care about yours. Again, kid. Midnight's young." }],
        nertz: {
          bots: [{ name: "Bettina \"The Squall\" Marlowe", avatar: "⚓", difficulty: "hard" }],
          rules: {},
          objective: { type: "time", target: 120 },
        },
        reward: { xp: 175, coins: 60 },
      },
      {
        id: "b11", locationId: "chowder", type: "blackjack", title: "Midnight Chowder Casino",
        intro: [
          { who: "doreen", text: "Welcome to the Midnight Chowder Casino. Sixty-five coins buys that roof a whole new hole-free lifestyle." },
          { who: "doreen", text: "Dealer shows a six. In chowder terms, that's broth with no clams. Weak. Press your luck." },
          { who: "crumbs", text: "(perches on the card shoe, staring at your hand with the eyes of a professional)" },
          { who: "gus", text: "(indoor voice, audible from the parking lot) GUS ANNOUNCES THE STAKES ARE HIGH AND SO IS THE HUMIDITY." },
          { who: "doreen", text: "Hit, stand, or soup? Say soup. Just once. I need to know the game can handle it." },
        ],
        win: [{ who: "doreen", text: "Twenty-one AGAIN? Take the money, and a chowder for the road. Take two. The roof can't hug you, but I can." }],
        lose: [{ who: "doreen", text: "House wins this round. Roof's still got its hole. Soup's still got its steam. Balance, of a sort." }],
        stake: 70,
        opponent: { name: "Doreen Vasquez", avatar: "🥣" },
        reward: { xp: 190, coins: 70, unlockTheme: "noir" },
      },
      {
        id: "b12", locationId: "marina", type: "poker", title: "All Hands on Deck",
        intro: [
          { who: "preston", text: "Welcome aboard The Humble Brag. Named ironically. The irony is also named Preston." },
          { who: "trent", text: "Before boarding, maritime liability waivers. Four copies. Also, please don't mention the water feature." },
          { who: "preston", text: "I ante the club key; you ante eighty coins and that ambient sense that you're winning. I want that too." },
          { who: "preston", text: "I never bluff. Bluffing is for people whose faces have range." },
          { who: "ferdinand", text: "(stowed away in a life jacket) Dear Mother. He drew three. THREE. His mustache is perspiring." },
          { who: "preston", text: "Ferdinand! You're supposed to be my second, not his. ...I'm reconsidering the seating chart entirely." },
        ],
        win: [{ who: "preston", text: "Take the key. Today's word is pronounced 'defeat,' and I will not be correcting anyone on it." }],
        lose: [{ who: "preston", text: "As expected. It's HAW-thorn — no. FETH-er-shaw. It changes when I'm winning. Ask anyone." }],
        stake: 95,
        opponent: { name: "Preston Featherstonhaugh III", avatar: "🎩" },
        reward: { xp: 210, coins: 85 },
      },
      {
        id: "b13", locationId: "club", type: "nertz", title: "The Founder's Day Qualifier",
        intro: [
          { who: "gus", text: "FOUNDER'S DAY QUALIFIER. FOUR PLAYERS ENTER. GUS DESCRIBES ALL OF THEM, INCLUDING HIMSELF." },
          { who: "milo", text: "Four-way Nertz is a 25% base win rate. Mine is 91%. Yours is whatever's left, split with these two. Sorry." },
          { who: "doreen", text: "I put espresso in the chowder. For everyone. As a courtesy. We are all so fast now." },
          { who: "milo", text: "Under two-thirty or it doesn't count, Founder's Day rules. Also my bedtime is at three." },
          { who: "betts", text: "Sign's down to one missing letter, kid. Win this and the water feature can finally mind its own business." },
          { who: "gus", text: "(indoor voice, louder than the espresso machine) AND THE KID QUALIFIES. GUS IS NOT CRYING. THAT'S SOMEONE ELSE. ALSO GUS." },
        ],
        win: [
          { who: "gus", text: "QUALIFIED. THE SANDPIPER SOC AL CLUB HAS ITS FINALIST. ONE LETTER LEFT. GUS CANNOT TAKE THE SUSPENSE." },
          { who: "milo", text: "91% said I'd win. I am recalculating my entire personality around being wrong." },
        ],
        lose: [{ who: "milo", text: "The numbers held! Barely! I'm as surprised as you are and I made the numbers up!" }],
        nertz: {
          bots: [
            { name: "Milo Pénzes", avatar: "📊", difficulty: "hard" },
            { name: "Gus \"Foghorn\" Tibbetts", avatar: "📢", difficulty: "hard" },
            { name: "Doreen Vasquez", avatar: "🥣", difficulty: "hard" },
          ],
          rules: {},
          objective: { type: "time", target: 150 },
        },
        reward: { xp: 230, coins: 100, title: "Founder's Day Finalist" },
      },
      {
        id: "b14", locationId: "club", type: "nertz", title: "The Nertz Royale",
        intro: [
          { who: "preston", text: "One hundred coins, the club's deed, and my dignity — which I keep on this velvet cushion, next to my deck." },
          { who: "trent", text: "Final waiver. Clause 12: in the event of an unbiased seagull, all pronunciation disputes are void. Nobody signed clause 12." },
          { who: "betts", text: "As the old sailors say: when the last card falls, the whole ocean holds its breath, and— kid, I've got nothing. I'm just proud of you. Go." },
          { who: "preston", text: "It's Fetherstan-HOFF today. Final answer. Possibly." },
          { who: "crumbs", text: "(perches between the two decks, visibly deciding something)" },
          { who: "you", text: "(You take a breath. The water feature, now nearly a pond, ripples once, like applause.)" },
        ],
        win: [
          { who: "crumbs", text: "(mid-match, plucks Preston's ace of spades and sets it, ceremonially, on your side of the table)" },
          { who: "preston", text: "THE BIRD IS BIASED. ...Fine. FINE. The club stands. It's 'Fanshaw.' It was 'Featherston-hoff' on Tuesday and I don't want to talk about it." },
          { who: "betts", text: "Sign's fixed, roof's patched, chowder's on every table, and the ledger finally has an entry in OUR favor. Deal us in." },
        ],
        lose: [
          { who: "preston", text: "The kelp conservatory thanks you for your donation. I'll frame this loss right next to my 2019 sash." },
          { who: "betts", text: "Not today. But the sign's still got one letter to go, and so do you. Same time tomorrow?" },
        ],
        nertz: {
          bots: [{ name: "Preston Featherstonhaugh III", avatar: "🎩", difficulty: "hard" }],
          rules: {},
          objective: { type: "win" },
        },
        reward: { xp: 260, coins: 120 },
      },
    ],
  };
})(typeof window !== "undefined" ? window : this);
